using System.Text;
using HarmonyLib;
using RimWorld;
using Verse;

namespace SeedsPlease
{
    [HarmonyPatch (typeof(DefGenerator), nameof(DefGenerator.GenerateImpliedDefs_PostResolve))]
    static class DefGenerator_GenerateImpliedDefs_PostResolve_Patch
    {
        static void Postfix() {
            var report = new StringBuilder();
            if (SeedDef.AddMissingSeeds(report)) {
                ResourceCounter.ResetDefs();

                Log.Warning("SeedsPlease :: Some Seeds were autogenerated." +
                            " Don't rely on autogenerated seeds," +
                            " share the generated xml for proper support.\n\n" +
                            report);
            }
        }
    }
}
